import Head from 'next/head'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'
import FormForSearch from './components/FormForSearch'
import ShowImage from './components/ShowImage'
import NotFound from './components/NotFound'
import About from './components/About'
import {getImageapod} from './api/operations'

const Home = (props) => {

  const current_data = () => {
    var data = new Date();
    var dia = String(data.getDate()).padStart(2, '0');
    var mes = String(data.getMonth() + 1).padStart(2, '0');
    var ano = data.getFullYear();
    var dataAtual = ano + '-' + mes + '-' + dia;
    return dataAtual
  }

  const state = {
    data: current_data()
  }
  const [apodCurrentData, setApodCurrentData] = useState()

  useEffect(() => {
    setApodCurrentData([])
    refresh()
  }, [])

 const refresh = (data) =>{
    getImageapod(current_data(),setApodCurrentData)
	}

	function handleSearch() {
		this.refresh(this.state.data)
	}

 

  return (
    <div className={styles.container}>
      <Head>
        <title></title>
        <meta name="description" content="Generated by create next app" />
      </Head>


      <main role={'main'} className='container'>
        <About />

        <div className="row">
          <FormForSearch onclick={handleSearch}/>
          {
            apodCurrentData !== undefined && apodCurrentData.date === current_data() ?
              <ShowImage 
                title={apodCurrentData.title}
                url={apodCurrentData.url} 
                explanation={apodCurrentData.explanation} 
              /> : <NotFound/>
          }
        </div>

      </main>
      <footer className='footer'>
        <div className='container'>
          <span className="text-muted">Desenvolvido por Gabriel flauzino Mota</span>
        </div>
      </footer>
    </div>
  )
}

export default Home;