import Head from 'next/head'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'
import FormForSearch from './components/FormForSearch'
import ShowImage from './components/ShowImage'
import NotFound from './components/NotFound'
import About from './components/About'
import {getImageapod} from './api/operations'

const Home = () => {

  const current_data = () => {
    var data = new Date();
    var dia = String(data.getDate()).padStart(2, '0');
    var mes = String(data.getMonth() + 1).padStart(2, '0');
    var ano = data.getFullYear();
    var dataAtual = ano + '-' + mes + '-' + dia;
    return dataAtual
  }

  const [apodCurrentData, setApodCurrentData] = useState()

  useEffect(() => {
    if (apodCurrentData === undefined) {
      refresh()
    }
  }, [])

 const refresh = () =>{
    getImageapod(current_data(),setApodCurrentData)
	}

	const search = (data) => {
    var dia = String(data.getDate()).padStart(2, '0');
    var mes = String(data.getMonth() + 1).padStart(2, '0');
    var ano = data.getFullYear();
    var dataAtual = ano + '-' + mes + '-' + dia;
    setApodCurrentData()
    getImageapod(dataAtual,setApodCurrentData)
	}

  return (
    <div className={styles.container}>
      <Head>
        <title></title>
        <meta name="description" content="Generated by create next app" />
      </Head>


      <main role={'main'} className='container'>
        <About />

        <div className="row">
          <FormForSearch search={search}/>
          {
            apodCurrentData !== undefined && apodCurrentData.code !== 400 ?
              <ShowImage 
                title={apodCurrentData.title}
                date={apodCurrentData.date}
                url={apodCurrentData.url} 
                explanation={apodCurrentData.explanation} 
              /> : <NotFound/>
          }
        </div>

      </main>
      <footer className='footer'>
        <div className='container'>
          <span className="text-muted">Desenvolvido por Gabriel flauzino Mota</span>
        </div>
      </footer>
    </div>
  )
}

export default Home;